
- hosts: localhost
  connection: local

  user: hoy

  sudo: true
  gather_facts: no

  tasks:
    - name: install vim, git
      apt: pkg={{item}} state=installed update_cache=yes
      with_items:
        - vim
        - git

    - name: install pypy
      apt: pkg={{item}} state=installed update_cache=yes
      with_items:
        - pypy
        - pypy-dev

    - name: Install some python2 module ( pip, virtualenv, numpy, matplotlib )
      apt: pkg={{item}} state=installed update_cache=yes
      with_items:
        - python-virtualenv
        - python-dev
        - python-pip
        - python-matplotlib
        - python-numpy

    - name: upgrade pip
      pip: name=pip state=latest

    - name: install ipython
      pip: name=ipython

    - name: install jedi
      pip: name=jedi

    - name: cython
      pip: name=cython

    # - name: install python3
    #   apt: pkg={{item}} state=installed update_cache=yes
    #   with_items:
    #     - python3
    #     - python3-dev
    #     - python3-pip

    # - name: install python3 matplotlib numby
    #   apt: pkg={{item}} state=installed update_cache=yes
    #   with_items:
    #     - python3-matplotlib
    #     - python3-numpy

    # - name: install cython3
    #   pip: name=cython executable=pip3

